### ISSUE TITLE
求能添加v免签

### ISSUE THREAD

**Issue by hcg101** [zfaka-plus/zfaka#176]
求能添加v免签 （或者其他的免签），这个比较实在，比当面付还实在

**Comment by huangfengye** [comment]
我已经加了啊。。。看我的仓库

**Comment by hcg101** [comment]
> 我已经加了啊。。。看我的仓库

感谢，我下载去对接一下

**Comment by 2399483979** [comment]
易支付：http://mzf.jvhezs.com/
（不用挂机，但是要到凌晨才结账）
码支付http://zf.jvhezs.com/
（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网
QQ讨论群：978095958

**Comment by 2399483979** [comment]
加QQ群：978095958




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zfaka-plus/zfaka"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zfaka-plus/zfaka] 求能添加v免签 (#176)





 
Closed #176.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
